# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.utils.translation import gettext_lazy as _

from pydantic import Field

from bazis.core.utils.schemas import BazisSettings


class Settings(BazisSettings):
    """
    The settings of bazis-ws. bazis-ws is not a Django app: the conf module is loaded with
    the settings of the installed Bazis packages, and the code reads the settings with
    their secure defaults, so that a project that lists its packages in BS_BAZIS_APPS
    without bazis-ws keeps them.
    """

    #: the common channel reaches every session that receives it: by default only the
    #: sessions of users (a session JWT); anonymous tokens are generated by the clients
    #: themselves, so anybody can open an anonymous session
    BAZIS_WS_ANONYMOUS_COMMON_CHANNEL: bool = Field(
        False, title=_('Anonymous WebSocket sessions receive the common channel')
    )


settings = Settings()
