# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import asyncio
import json
import logging
from typing import Any

from django.utils.translation import gettext as _

from starlette.endpoints import WebSocketEndpoint
from starlette.routing import WebSocketRoute
from starlette.status import WS_1011_INTERNAL_ERROR
from starlette.websockets import WebSocket

from . import COMMON_CHANNEL
from .utils import (
    UserError,
    get_anonymous_channel,
    get_redis_async,
    get_user_from_token_async,
    is_user_token,
)


logger = logging.getLogger(__name__)


class WsEndpoint(WebSocketEndpoint):
    """
    A WebSocket that delivers the messages of a channel to the client.

    The client starts a session with a token, in the `token` query parameter or in a
    `{"token": ...}` message: a user session JWT subscribes to the channel of the user,
    any other token is an anonymous token (16-128 characters `A-Z a-z 0-9 _ -` generated by
    the client) and subscribes to an anonymous channel of its own. Every session also
    receives the common channel. `{"type": "ping"}` is answered with `{"type": "pong"}`.

    While a session is running, its key is kept in Redis (see `UserWsMixin.is_online`).
    If Redis fails, the socket is closed with code 1011 so that the client reconnects.
    """

    encoding = 'json'
    #: seconds between refreshes of the session key, which expires after twice the interval
    online_interval: int = 5

    session_key: str | None
    channel_name: str | None

    def __init__(self, scope, receive, send):
        super().__init__(scope, receive, send)
        self.active_tasks: list[asyncio.Task] = []
        self.session_key = None
        self.channel_name = None

    @property
    def is_running(self) -> bool:
        return any(not task.done() for task in self.active_tasks)

    async def on_connect(self, websocket: WebSocket):
        await websocket.accept()
        logger.debug('WS: connected')
        if token := websocket.query_params.get('token'):
            await self.session_start(websocket, token)

    async def on_receive(self, websocket: WebSocket, data: Any) -> None:
        if isinstance(data, str):
            try:
                data = json.loads(data)
            except ValueError:
                logger.debug('WS: a message that is not JSON is ignored')
                return

        if not isinstance(data, dict):
            return

        if data.get('type') == 'ping':
            await websocket.send_json({'type': 'pong'})
            return

        if token := data.get('token'):
            await self.session_start(websocket, token)

    async def on_disconnect(self, websocket: WebSocket, close_code: int):
        logger.debug('WS: disconnected with code %s', close_code)
        await self.session_stop(websocket)

    async def session_start(self, websocket: WebSocket, token: str):
        await self.session_stop(websocket)

        try:
            if not isinstance(token, str):
                raise UserError(message='Invalid token', code='invalid_token')
            if is_user_token(token):
                user = await get_user_from_token_async(token)
                session_key, channel_name = user.ws_session, user.user_channel
            else:
                channel_name = get_anonymous_channel(token)
                session_key = f'{channel_name}:session'
        except UserError as exc:
            logger.info('WS: session rejected: %s', exc.code)
            await websocket.send_json({'type': 'error', 'code': exc.code, 'detail': exc.message})
            return
        except Exception:
            logger.exception('WS: session start failed')
            await websocket.send_json(
                {'type': 'error', 'code': 'internal_error', 'detail': _('Internal server error')}
            )
            return

        logger.debug('WS: session started on %s', channel_name)
        self.session_key = session_key
        self.channel_name = channel_name
        self.active_tasks = [
            asyncio.create_task(self.task_online_update(websocket)),
            asyncio.create_task(self.task_listen_queue(websocket)),
        ]

    async def session_stop(self, websocket: WebSocket, code: int | None = None):
        tasks, self.active_tasks = self.active_tasks, []
        current = asyncio.current_task()
        tasks = [task for task in tasks if task is not current]
        for task in tasks:
            task.cancel()
        await asyncio.gather(*tasks, return_exceptions=True)

        if self.session_key:
            try:
                await get_redis_async().delete(self.session_key)
            except Exception:
                logger.exception('WS: failed to delete the session key')
        self.session_key = None
        self.channel_name = None

        if code:
            await websocket.close(code)

    async def _fail(self, websocket: WebSocket):
        """
        Closes the socket after a background task of the session failed.
        """
        try:
            await websocket.close(WS_1011_INTERNAL_ERROR)
        except Exception:
            logger.debug('WS: the socket is already closed')

    async def task_online_update(self, websocket: WebSocket):
        try:
            while True:
                await get_redis_async().set(self.session_key, '1', ex=self.online_interval * 2)
                await asyncio.sleep(self.online_interval)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception('WS: failed to refresh the session key')
            await self._fail(websocket)

    async def task_listen_queue(self, websocket: WebSocket):
        try:
            async with get_redis_async().pubsub(ignore_subscribe_messages=True) as pubsub:
                await pubsub.subscribe(self.channel_name, COMMON_CHANNEL)
                async for message in pubsub.listen():
                    if out_message := message.get('data'):
                        if isinstance(out_message, bytes):
                            out_message = out_message.decode()
                        await websocket.send_json({'type': 'data', 'data': out_message})
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception('WS: failed to deliver the channel messages')
            await self._fail(websocket)


ws_route = WebSocketRoute('/ws', WsEndpoint)
