# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import asyncio
import json
import logging
from typing import Any

from django.conf import settings
from django.utils.translation import gettext as _

from starlette.endpoints import WebSocketEndpoint
from starlette.routing import WebSocketRoute
from starlette.status import WS_1008_POLICY_VIOLATION, WS_1011_INTERNAL_ERROR
from starlette.websockets import WebSocket, WebSocketState

from . import COMMON_CHANNEL
from .utils import (
    UserError,
    get_anonymous_channel,
    get_redis_async,
    get_user_from_token_async,
    is_user_token,
)


logger = logging.getLogger(__name__)


class WsEndpoint(WebSocketEndpoint):
    """
    A WebSocket that delivers the messages of a channel to the client.

    The client starts a session with a token, in the `token` query parameter or in a
    `{"token": ...}` message: a user session JWT subscribes to the channel of the user and
    to the common channel, any other token is an anonymous token (16-128 characters
    `A-Z a-z 0-9 _ -` generated by the client) and subscribes to an anonymous channel of
    its own (and to the common channel only with BAZIS_WS_ANONYMOUS_COMMON_CHANNEL).
    `{"type": "subscribed"}` is sent once the subscription is active: the messages
    published from then on are delivered. `{"type": "ping"}` is answered with
    `{"type": "pong"}`.

    While a session is running, its key is kept in Redis (see `UserWsMixin.is_online`).
    A session that cannot run closes the socket after an `{"type": "error"}` message: with
    code 1008 when the token is refused (a new connection needs another token), with code
    1011 when the server fails (the session start or Redis; the client reconnects).
    """

    encoding = 'json'
    #: seconds between refreshes of the session key, which expires after twice the interval
    online_interval: int = 5

    session_key: str | None
    #: the own channel of the session (of the user or of the anonymous token)
    channel_name: str | None
    #: whether the session also receives the common channel
    receives_common: bool

    def __init__(self, scope, receive, send):
        super().__init__(scope, receive, send)
        self.active_tasks: list[asyncio.Task] = []
        self.session_key = None
        self.channel_name = None
        self.receives_common = False

    @property
    def is_running(self) -> bool:
        return any(not task.done() for task in self.active_tasks)

    async def on_connect(self, websocket: WebSocket):
        await websocket.accept()
        logger.debug('WS: connected')
        if token := websocket.query_params.get('token'):
            await self.session_start(websocket, token)

    async def on_receive(self, websocket: WebSocket, data: Any) -> None:
        if websocket.application_state != WebSocketState.CONNECTED:
            # the server closed the socket (a refused token, a failure): the messages that
            # the client sent before it received the close are ignored
            return

        if isinstance(data, str):
            try:
                data = json.loads(data)
            except ValueError:
                logger.debug('WS: a message that is not JSON is ignored')
                return

        if not isinstance(data, dict):
            return

        if data.get('type') == 'ping':
            await websocket.send_json({'type': 'pong'})
            return

        if token := data.get('token'):
            await self.session_start(websocket, token)

    async def on_disconnect(self, websocket: WebSocket, close_code: int):
        logger.debug('WS: disconnected with code %s', close_code)
        await self.session_stop(websocket)

    async def session_start(self, websocket: WebSocket, token: str):
        await self.session_stop(websocket)

        try:
            if not isinstance(token, str):
                raise UserError(message='Invalid token', code='invalid_token')
            if is_user_token(token):
                user = await get_user_from_token_async(token)
                session_key, channel_name = user.ws_session, user.user_channel
                receives_common = True
            else:
                channel_name = get_anonymous_channel(token)
                session_key = f'{channel_name}:session'
                # anybody can open an anonymous session with a token of their own
                receives_common = getattr(settings, 'BAZIS_WS_ANONYMOUS_COMMON_CHANNEL', False)
        except UserError as exc:
            logger.info('WS: session rejected: %s', exc.code)
            await websocket.send_json({'type': 'error', 'code': exc.code, 'detail': exc.message})
            await self._close(websocket, WS_1008_POLICY_VIOLATION)
            return
        except Exception:
            logger.exception('WS: session start failed')
            await websocket.send_json(
                {'type': 'error', 'code': 'internal_error', 'detail': _('Internal server error')}
            )
            await self._close(websocket, WS_1011_INTERNAL_ERROR)
            return

        logger.debug('WS: session started on %s', channel_name)
        self.session_key = session_key
        self.channel_name = channel_name
        self.receives_common = receives_common
        self.active_tasks = [
            asyncio.create_task(self.task_online_update(websocket)),
            asyncio.create_task(self.task_listen_queue(websocket)),
        ]

    async def session_stop(self, websocket: WebSocket, code: int | None = None):
        tasks, self.active_tasks = self.active_tasks, []
        for task in tasks:
            task.cancel()
        await asyncio.gather(*tasks, return_exceptions=True)

        if self.session_key:
            try:
                await get_redis_async().delete(self.session_key)
            except Exception:
                logger.exception('WS: failed to delete the session key')
        self.session_key = None
        self.channel_name = None
        self.receives_common = False

        if code:
            await websocket.close(code)

    async def _close(self, websocket: WebSocket, code: int):
        """
        Closes the socket of a session that cannot run (see the class docstring for the
        codes); the socket may already be closed.
        """
        try:
            await websocket.close(code)
        except Exception:
            logger.debug('WS: the socket is already closed')

    async def task_online_update(self, websocket: WebSocket):
        try:
            while True:
                await get_redis_async().set(self.session_key, '1', ex=self.online_interval * 2)
                await asyncio.sleep(self.online_interval)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception('WS: failed to refresh the session key')
            await self._close(websocket, WS_1011_INTERNAL_ERROR)

    async def task_listen_queue(self, websocket: WebSocket):
        try:
            channels = [self.channel_name] + ([COMMON_CHANNEL] if self.receives_common else [])
            async with get_redis_async().pubsub() as pubsub:
                await pubsub.subscribe(*channels)
                # the subscription is active once Redis confirmed every channel: a message
                # published before is not delivered
                unconfirmed = len(channels)
                async for message in pubsub.listen():
                    if message['type'] == 'subscribe':
                        unconfirmed -= 1
                        if unconfirmed == 0:
                            await websocket.send_json({'type': 'subscribed'})
                    elif message['type'] == 'message' and (out_message := message['data']):
                        if isinstance(out_message, bytes):
                            out_message = out_message.decode()
                        await websocket.send_json({'type': 'data', 'data': out_message})
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception('WS: failed to deliver the channel messages')
            await self._close(websocket, WS_1011_INTERNAL_ERROR)


ws_route = WebSocketRoute('/ws', WsEndpoint)
